version: "3.8"

services:
  monitor_server:
    image: monitor-server:1.5
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
    ports:
      - target: 5566
        published: 5566
        protocol: tcp
        mode: ingress

    volumes:
      - monitor_data:/app/screenshots

volumes:
  monitor_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.17.220,rw"
      device: ":/mnt/nfs/shared/monitor"

