version: "3.8"

services:
  monitor_server:
    image: dregistrygui.uskoinc.com/monitor-server:2.0
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
    ports:
      - target: 5566
        published: 5566
        protocol: tcp
        mode: ingress
    volumes:
      - /mnt/nfs/shared/monitor:/app/screenshots